hopefully fix compilation error. (it compiles on my machine but not in github)
```
[error] /home/runner/work/workbench-libs/workbench-libs/google/src/main/scala/org/broadinstitute/dsde/workbench/google/HttpGoogleIamDAO.scala:227:28: missing argument list for method when400WithDoesNotExistMessage in object RetryPredicates
[error] Unapplied methods are only converted to functions when a function type is expected.
[error] You can make this conversion explicit by writing `when400WithDoesNotExistMessage _` or `when400WithDoesNotExistMessage(_)` instead of `when400WithDoesNotExistMessage`.
[error]       basePredicateList :+ when400WithDoesNotExistMessage
[error]                            ^
```